[tool.isort]
profile = "black"

[tool.poetry]
name = "cli-ui"
version = "0.13.0"
description = "Build Nice User Interfaces In The Terminal"
authors = ["Dimitri Merejkowsky <d.merej@gmail.com>"]
readme = "README.rst"

[tool.poetry.dependencies]
# Keep this in sync with .github/workflows/
python = "^3.6"
colorama = "^0.4.1"
tabulate = "^0.8.3"
unidecode = "^1.0.23"

[tool.poetry.dev-dependencies]
# doc
sphinx  = "^3.0.4"
ghp-import = "^0.5.5"

# linters
black = "19.10b0"
mypy = "^0.800"
pyflakes = "2.1.1"

# tests
attrs = "^19.3"
codecov = "^2.1"
coverage = "^5.2"
pytest = "^6.2.1"
pytest-cov = "^2.10"
safety = "^1.9.0"
isort = "^5.7.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
