[tool.isort]
profile = "black"

[tool.poetry]
name = "cli-ui"
version = "0.16.1"
description = "Build Nice User Interfaces In The Terminal"
readme = "README.rst"
authors = ["Dimitri Merejkowsky <dimitri@dmerej.info>"]
license = "BSD-3-Clause"
repository = "https://github.com/dmerejkowsky/python-cli-ui"
documentation = "https://dmerejkowsky.github.io/python-cli-ui/"

[tool.poetry.urls]
Changelog = "https://dmerejkowsky.github.io/python-cli-ui/changelog.html"
Issues = "https://github.com/dmerejkowsky/python-cli-ui/issues"

[tool.poetry.dependencies]
# Keep this in sync with .github/workflows/
python = "^3.7"

colorama = "^0.4.1"
tabulate = "^0.8.3"
unidecode = "^1.0.23"

[tool.poetry.dev-dependencies]
# Task runner
invoke = "^1.5.0"

# Tests
pytest = "^7.0.0"
pytest-cov = "^3.0.0"

# Linters
black = "21.10b0"
flake8 = "4.0.1"
flake8-bugbear = "^21.9.2"
flake8-comprehensions = "^3.7.0"
pep8-naming = "^0.12.1"
isort = "^5.7.0"
types-tabulate = "^0.1.0"
mypy = "0.940"

# Deps scanning
safety = "^1.9.0"

# Documentation
sphinx  = "^4.1.2"
sphinx-autobuild = "2021.3.14"
ghp-import = "^0.5.5"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
